### PR TITLE
Deal with local and external storage paths being the same

### PR DESCRIPTION
**Pull request by micahwoodard**
First stab at trying to deal with the condition if local and external storage is the same. This has been happening on the mindscope dispim and it just transfers images to a different folder on the same external drive.

### CODE REVIEW

**Comment by micahwoodard** [comment]
Final version for me. Works when local != ext and when local == ext. One note is that if local == ext, it set the external drive equal to None. I'm not sure the behaviour on the exaspim but on the dispims if ext == None then the transfer process does not happen. Happy to change to better accomadate the two systems

**Comment by micahwoodard** [comment]
Just following up on whether we can merge this to main?

**Review by Poofjunior — CHANGES_REQUESTED** [review]
Oof; ok, it looks like we don't need to do this and can hand this in one line of code in the respective spim repos:
https://github.com/AllenNeuralDynamics/exa-spim-control/blob/main/exaspim/exaspim.py#L360
The above should be:
````python
if img_storage_dir and img_storage_dir != local_storage_dir:
````
Let's confirm that the above works, and if yes, let's remove these changes from spim-core, but keep the tigerbox stuff.

**Comment by Poofjunior** [comment]
@micahwoodard have a look at my request to merge these changes into your branch.
https://github.com/AllenNeuralDynamics/spim-core/pull/20

If that's a go, let's merge #20 and then lets merge this one.

**Pull request merged**
